// data.js - Base de datos de usuarios de LagunApp
const demoUsers = [
  {id:1,name:"Ane Etxebarria",username:"ane_e",age:24,city:"Bilbo",gender:"Emakumea",
   bio:"Futbolzalea eta musika zalea. Kafea eta elkarrizketak gustatzen zaizkit!",
   food:["🍕 Pizza","🧆 Pintxoak"],sport:["⚽ Futbola","🏃 Korrika"],
   free:["🎬 Zinema/Serieak","☕ Lagunartea"],music:["🎵 Indie","🎸 Rock"],
   pers:["😄 Alaia eta baikorra","🎉 Extrovertitua"],plans:["🍻 Tabernara joan","🎵 Kontzertura"],
   color:"from-orange-400 to-red-500",avatar:"A"},
  {id:2,name:"Mikel Goikoetxea",username:"mikel_g",age:27,city:"Donostia",gender:"Gizona",
   bio:"Mendira joatea eta bideojokoak gustuko ditut. Lasaia baina fun!",
   food:["🥩 Haragia","🍔 Hamburgesa"],sport:["🏔️ Mendizaletasuna","🚴 Txirrindularitza"],
   free:["🎮 Bideojokoak","💻 Teknologia"],music:["🤘 Metal","🎸 Rock"],
   pers:["😌 Lasaia eta orekatua","🔒 Introvertitua"],plans:["🏔️ Mendira","🎮 Partida jolasten"],
   color:"from-violet-500 to-indigo-500",avatar:"M"},
  {id:3,name:"Leire Azpeitia",username:"leire_az",age:22,city:"Gasteiz",gender:"Emakumea",
   bio:"Arte sormena eta txirrindularitza. Natura maite dut.",
   food:["🥗 Entsalada","🌱 Beganoa"],sport:["🚴 Txirrindularitza","🧘 Yoga"],
   free:["🎨 Arte Sormena","🌱 Landareak"],music:["🎤 Pop","🎵 Indie"],
   pers:["🎨 Sortzailea","⭐ Baikorra"],plans:["🏖️ Hondartzara","🎨 Kultura eta museoak"],
   color:"from-emerald-400 to-teal-500",avatar:"L"},
  {id:4,name:"Jon Urrutia",username:"jon_u",age:30,city:"Bilbo",gender:"Gizona",
   bio:"Sukaldaritza da nire pasioa! Podcast eta jazz zalea.",
   food:["🍝 Pasta","🍰 Postreak"],sport:["🏊 Igeriketa","🏸 Padela"],
   free:["👨‍🍳 Sukaldaritza","🎙️ Podcast"],music:["🎷 Jazz","🎻 Klasikoa"],
   pers:["😄 Alaia eta baikorra","🤗 Enpatikoa"],plans:["🍽️ Jatetxera","☕ Kafetegian hitz egin"],
   color:"from-amber-400 to-orange-500",avatar:"J"},
  {id:5,name:"Miren Zubiaurre",username:"miren_z",age:19,city:"Zarautz",gender:"Emakumea",
   bio:"Surf eta musika elektronikoa! Itsasoa eta festa gustatzen zaizkit.",
   food:["🍣 Sushi","🍔 Hamburgesa"],sport:["🏄 Surf","💃 Dantza"],
   free:["📷 Argazkilaritza","✈️ Bidaiak"],music:["💿 Elektronika/EDM","🎺 Reggaeton"],
   pers:["🎉 Extrovertitua","🏕️ Abenturazalea"],plans:["🏖️ Hondartzara","🍻 Tabernara joan"],
   color:"from-cyan-400 to-blue-500",avatar:"Mz"},
  {id:6,name:"Iñaki Larrazabal",username:"inaki_l",age:25,city:"Durango",gender:"Gizona",
   bio:"Coding eta Rock. Full-stack garatzailea naiz.",
   food:["🍕 Pizza","🍔 Hamburgesa"],sport:["🏃 Korrika","🏋️ Gimnasioa"],
   free:["💻 Teknologia","🎸 Musika jotzen"],music:["🎸 Rock","🤘 Metal"],
   pers:["🎨 Sortzailea","📖 Jakin-mina"],plans:["🎵 Kontzertura","🎮 Partida jolasten"],
   color:"from-slate-500 to-gray-700",avatar:"I"},
  {id:7,name:"Amaia Bergara",username:"amaia_b",age:28,city:"Donostia",gender:"Emakumea",
   bio:"Zinema eta bidaiak. Mundua ikusi nahi dut.",
   food:["🍣 Sushi","🥘 Cocido"],sport:["🧘 Yoga","🏔️ Mendizaletasuna"],
   free:["🎬 Zinema/Serieak","✈️ Bidaiak"],music:["🎤 Pop","🎷 Jazz"],
   pers:["😌 Lasaia eta orekatua","🤗 Enpatikoa"],plans:["🎬 Zinemara","🎭 Kultura"],
   color:"from-rose-400 to-pink-500",avatar:"Am"},
  {id:8,name:"Ekaitz Aranburu",username:"ekaitz_a",age:21,city:"Iruñea",gender:"Gizona",
   bio:"Saskibaloia eta hip-hop. Dantzatzen ere gustuko dut!",
   food:["🍔 Hamburgesa","🌮 Tacos"],sport:["🏀 Saskibaloia","💃 Dantza"],
   free:["🎮 Bideojokoak","📷 Argazkilaritza"],music:["🎧 Hip-Hop/Trap","💿 Elektronika"],
   pers:["😄 Alaia eta baikorra","🎉 Extrovertitua"],plans:["🍻 Tabernara joan","🏃 Kiroletan"],
   color:"from-purple-500 to-fuchsia-500",avatar:"E"}
];
